In [1]:
!pip install numpy

# Using NumPy

Once you've  installed NumPy you can import 

In [1]:
import numpy as np

Numpy has many built-in function and capabilities. we don't cover them all but instead we will vector

In [11]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [12]:
a = np.array(my_list)

In [13]:
a

array([1, 2, 3, 4, 5])

In [14]:
type(a)

numpy.ndarray

In [15]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [16]:
b = np.array(my_matrix)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
#Array summary
print('The Dimension of array', b.ndim)   #Dimensions of given array is true

The Dimension of array 2


In [18]:
print('Size of the array :', b.size)    #number of elements in array

Size of the array : 12


In [19]:
print('the datatype of element: ', b.dtype)    #datatype od element of array

the datatype of element:  int32


In [20]:
print('The datatype of array', type(b))

The datatype of array <class 'numpy.ndarray'>


In [21]:
print('The shape: ', b.shape)

The shape:  (3, 4)


In [23]:
a    #1 dimensional array

array([1, 2, 3, 4, 5])

In [25]:
print('The Dimension of array', a.ndim)

The Dimension of array 1


In [26]:
print('Size of the array :', a.size)

Size of the array : 5


In [27]:
print('the datatype of element: ', a.dtype)

the datatype of element:  int32


In [29]:
print('The datatype of array', type(a))

The datatype of array <class 'numpy.ndarray'>


In [30]:
print('The shape: ', a.shape)

The shape:  (5,)


In [31]:
c = np.array([[[[1,2,3,4,5],[6,7,8,9,10]]]])
c

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [32]:
print(c.ndim)

4


In [33]:
print(c.size)

10


In [34]:
# Creat the above array
#Give dimensions of array
# in each dimension get number of elements

## Built-in Methods

there are lots of built-in ways to generate arrays

## arange

Return evenly spaced values within a given interval.

In [35]:
np.arange(15)    #end

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
np.arange(0,15)   #start and  end

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
np.arange(0,11,2)   #start end and step

array([ 0,  2,  4,  6,  8, 10])

### Reshape Function

In [39]:
np.arange(1,16).reshape(15,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [40]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [41]:
np.arange(1,16).reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [48]:
np.arange(1,16).reshape(5,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

### Zeros and Ones

In [42]:
a =np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
np.zeros(3)

array([0., 0., 0.])

In [50]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.zeros((4,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [52]:
np.ones(3)

array([1., 1., 1.])

In [53]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.ones((4,5,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

### linspace

Return evenly spaced numbers over a specified interval

In [57]:
np.linspace(0,25, num=20)    #start  # end(Here end is included) and default elements

array([ 0.        ,  1.31578947,  2.63157895,  3.94736842,  5.26315789,
        6.57894737,  7.89473684,  9.21052632, 10.52631579, 11.84210526,
       13.15789474, 14.47368421, 15.78947368, 17.10526316, 18.42105263,
       19.73684211, 21.05263158, 22.36842105, 23.68421053, 25.        ])

In [59]:
np.linspace(0,200,10,retstep=True)

(array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
         88.88888889, 111.11111111, 133.33333333, 155.55555556,
        177.77777778, 200.        ]),
 22.22222222222222)

In [61]:
np.linspace(0,150,25,retstep=False)

array([  0.  ,   6.25,  12.5 ,  18.75,  25.  ,  31.25,  37.5 ,  43.75,
        50.  ,  56.25,  62.5 ,  68.75,  75.  ,  81.25,  87.5 ,  93.75,
       100.  , 106.25, 112.5 , 118.75, 125.  , 131.25, 137.5 , 143.75,
       150.  ])

### Eye

creat an identity matrix

In [63]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Random

Numpy also has lots of ways to creat random number arrays:

### rand

creat an array of the given shape and populate it with random samples from a uniform distribution over ``[0,1)''

In [64]:
np.random.rand(4)

array([0.81063065, 0.96896494, 0.24757392, 0.58542926])

In [65]:
np.random.rand(5,3)

array([[0.73238273, 0.69662648, 0.49139292],
       [0.40566878, 0.67459721, 0.12347412],
       [0.19240602, 0.61048689, 0.32366044],
       [0.47782942, 0.51734051, 0.89288197],
       [0.74282762, 0.97640448, 0.27155125]])

In [66]:
np.random.rand(3,3)

array([[0.48447368, 0.76992225, 0.20162173],
       [0.32657914, 0.59905757, 0.46925707],
       [0.20152513, 0.12119552, 0.03224545]])

### randn

Return a sample from the "standard normal" distribution. Unlike rand which is uniform:

In [67]:
np.random.randn(4)

array([-0.34539056, -0.44513305, -0.27454151,  0.11082196])

In [68]:
np.random.randn(3,4)

array([[ 0.53754747, -1.41035721,  1.58063134, -2.02440254],
       [-2.75228038,  0.38529711, -2.09360018,  1.25802436],
       [-0.72598457, -0.62367473, -2.82550591, -1.08051391]])

### randint

return random integers from low (inclusive) to high (exclusive)

In [69]:
np.random.randint(1,100)

13

In [70]:
np.random.randint(1,100,10)

array([ 4,  3, 77, 22, 64, 38, 48,  7,  8, 29])

## Array attributes and Methos

lets discuss some usefull attributes and methods

In [75]:
arr1 = np.arange(20)
arr2 = np.random.randint(0,100,10)

In [77]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [78]:
arr2

array([18, 26, 34, 92, 11, 96, 60, 74,  1, 90])

### max,min,argmax,argmin

These are useful methods for finding max or min values.

In [79]:
arr1.max()

19

In [80]:
arr2.min()

1

In [81]:
arr1.min(0)

0

In [82]:
arr2.max()

96

In [83]:
arr1.argmax()

19

In [84]:
arr1.argmin()

0

In [88]:
print(arr2.argmax())  #Index location of highest element
print(arr2.argmin())  #Gives the lowest elements of array

5
8
