## Bracket Indexing and Selection

The simplest way to pick one or some elements of an array looks very similar to python list:

In [1]:
import numpy as np

In [12]:
#get a value at an index
arr = np.arange(20)
print(arr)
print(arr[9])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
9


## Broadcasting

In [13]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [14]:
#Setting a value with index range(Broadcasting)
arr[:] =100

#show
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [15]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [16]:
arr2 = np.array([4,5,6])
arr2

array([4, 5, 6])

In [17]:
arr1+arr2

array([5, 7, 9])

In [18]:
arr2-arr1

array([3, 3, 3])

In [19]:
arr1*arr2

array([ 4, 10, 18])

In [20]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [21]:
#Creat 2 list and check any mathematical operation
a=[12,23,34,56]
b=[23,34,45,56]
a+b

[12, 23, 34, 56, 23, 34, 45, 56]

In [22]:
#copy operation
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [23]:
arr[3:] =100
arr

array([  1,   2,   3, 100, 100])

In [24]:
arr1 = arr    # Assigning the elements of arr to arr1  #Backup

In [25]:
arr1

array([  1,   2,   3, 100, 100])

In [26]:
arr1[3:]=500
arr1    #New array

array([  1,   2,   3, 500, 500])

In [27]:
arr

array([  1,   2,   3, 500, 500])

In [28]:
arr2=arr.copy()
arr2

array([  1,   2,   3, 500, 500])

In [29]:
arr

array([  1,   2,   3, 500, 500])

In [30]:
arr2[3:]= 100
arr2

array([  1,   2,   3, 100, 100])

In [31]:
arr   #Restored the property of backup

array([  1,   2,   3, 500, 500])

In [32]:
#Flitering condition

arr = np.array([1,2,1010,4,8,18,7])

In [33]:
np.where(arr>100)    #Where function outputs index location of condition

(array([2], dtype=int64),)

In [34]:
np.where(arr<100)    #only index location not values

(array([0, 1, 3, 4, 5, 6], dtype=int64),)

## Indexing on 2D array (matrices)

The general format is an_2d[row,col].

In [35]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
arr_2d[1]

array([20, 25, 30])

In [37]:
arr_2d[1][0]

20

In [38]:
arr_2d[2,2]

45

In [39]:
#2D array slicing

#shape (2,2) from top right corner
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [40]:
arr_2d[ :, 1:2 ]

array([[10],
       [25],
       [40]])

In [41]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# Selection

let's briefly go over how to use brackets for selection based off of comparison operators.

In [42]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

# NumPy Operations

### Arthematic

You can perform array operation with array arithmetic or scalar with array

In [44]:
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [46]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [47]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
# Warning on division by zero, but not an error
# just replaced with NaN --> not a number

arr/arr

C:\Users\sagar\AppData\Local\Temp/ipykernel_12432/840050445.py:4: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [49]:
#Also warning but not an error instead infinity (Reciprocal)

1/arr

C:\Users\sagar\AppData\Local\Temp/ipykernel_12432/719251524.py:3: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [50]:
arr ** 3   #Power of operator

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859], dtype=int32)

## Universal array function

In [51]:
# Taking square roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [52]:
#Calculating exponential  (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [53]:
np.max(arr)  #same as arr.max()

19

In [54]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [55]:
np.log(arr)

C:\Users\sagar\AppData\Local\Temp/ipykernel_12432/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [6]:
# Conversion from degree to radians
d = np.arange(0,120,30).reshape(2,2)
d

array([[ 0, 30],
       [60, 90]])

In [13]:
rad=d*np.pi/180   (#angle to radian conversion)
rad

SyntaxError: unexpected EOF while parsing (Temp/ipykernel_12932/2136357114.py, line 2)

In [9]:
np.sin(rad)

NameError: name 'rad' is not defined

In [10]:
np.log(rad)

NameError: name 'rad' is not defined

In [11]:
np.cos(rad)

NameError: name 'rad' is not defined

In [12]:
np.sec(rad)

AttributeError: module 'numpy' has no attribute 'sec'